### ISSUE TITLE
Week 15   2018/03/05 to 2018/03/12

### ISSUE THREAD

**Issue by Pokemod97** [ReswitchedWeekly/ReswitchedWeekly.github.io#30]
If you're working on something interesting, post here.

**Comment by roblabla** [comment]
Yesterday night, something amazing happened: Schala (@Daeken) released expldr, a bug that crashes any builtin sysmodules (and well, precisely, any modules that has a smaller handle table). This means two things:

- It is now possible to dump modules on 1.0.0-3.0.0 (included)
- It is possible to get **full** fs permissions. This means we can now do things like dump the NAND, edit save filese, etc... (DO NOTE THAT THIS IS DANGEROUS, AND CAN RESULT IN A BRICK)

**Comment by roblabla** [comment]
Meanwhile, I'm making big progress on megaton hammer. CRT0 now works. I'm in the process of making IPC works sufficiently well to get a BSD socket up.

**Comment by Pokemod97** [comment]
I’m working on an AUR package.

**Comment by Pokemod97** [comment]
https://pastebin.com/VGRSkMTe

**Comment by Pokemod97** [comment]
http://www.ktemkin.com/

**Comment by dubyadud** [comment]
Retr0id is working on a desume core, planning to release it soon.

**Comment by Valeri0p** [comment]
So just you know, the bootrom has been leaked :(
