### ISSUE TITLE
Bi-Week 17 - 2018/05/10 to 2018/05/23

### ISSUE THREAD

**Issue by roblabla** [ReswitchedWeekly/ReswitchedWeekly.github.io#37]
Please post any interesting news you come across here. Whether it comes from you or from someone else :)

**Comment by Valeri0p** [comment]
Again, thanks for your effort in keeping us updated, especially on the behind the scenes section :D
A little question btw: Twili will be the primary way of loading homebrew on Atmosphere, isn't it? 

About the joycon drivers in Linux:
https://mobile.twitter.com/ShinyQuagsire/status/995570539086331905

**Comment by roblabla** [comment]
@Valeri0p Woop, sorry for not answering your question, I didn't see it. I'm not sure if the end-goal of twili is to be the primary way of loading homebrew. I hope it will be, as it is **vastly** cleaner from the existing solution, providing proper process isolation among other benefits.

**Comment by Valeri0p** [comment]
I hope so, thanks for your reply!
