### ISSUE TITLE
Bi-Week 18 - 2018/05/25 to 2018/06/06

### ISSUE THREAD

**Issue by roblabla** [ReswitchedWeekly/ReswitchedWeekly.github.io#38]
Please post any interesting news you come across here. Whether it comes from you or from someone else :)

**Comment by Adubbz** [comment]
Was recommended I post this here :P https://github.com/Adubbz/Gag-Order. Removes Supernag, early release, may be bugs, etc. etc.

**Comment by StevenMattera** [comment]
Not sure if it's considered news until it gets merged in, but I put in a pull request to get touch controls added to hbmenu. Honestly makes navigating hbmenu much easier in my opinion. https://youtu.be/6a23DBWMF-c

**Comment by natinusala** [comment]
First release of Lakka for the Switch, a retrogaming distribution : https://lakka-switch.github.io/documentation/

(I guess it's the first Linux distribution made especially for the Switch ?)

**Comment by natinusala** [comment]
perillamint made this : https://gitlab.com/perillamint/nx-fwextract

Allows to extract Bluetooth & Wi-Fi chip firmware from Horizon - along with some kernel patches, this enables fully working and full speed Bluetooth on Linux (it can be used for audio, for instance)

**Comment by Valeri0p** [comment]
We finally got a battery de-sync [software fix/workaround](https://github.com/crystalseedgba/BatteryFix/blob/master/fusee/src/main.c) , and found the [source](https://github.com/fail0verflow/switch-linux/issues/6) of the problem!

Ps: are you going to make other articles? They are fantastic for see what's going on under the hood!

**Comment by natinusala** [comment]
The fix in Hekate 3.0 is the true fix (setting the register back to 0x92). The other one fixed it but it was just a side effect of the power cycling.

**Comment by takashi1kun** [comment]
Is the biweekly dead?

**Comment by natinusala** [comment]
I feel like the Trinket M0 hardmod is worth an entry here

**Comment by gerd2002** [comment]
@takashi1kun I just did the writeup with permission from roblabla, see #40 for the status of the PR

**Comment by thomleg50** [comment]
@gerd2002 you forgot my loader ?
https://thomleg50.github.io/atmosphere-loader
