### ISSUE TITLE
$INTERVAL 19 - from 2018/7/11

### ISSUE THREAD

**Issue by gerd2002** [ReswitchedWeekly/ReswitchedWeekly.github.io#39]
Please post any interesting news you come across here. Whether it comes from you or from someone else :)

If it comes from someone else, please credit the original creator. Links are much appreciated!

*Planned post date will be 2018/7/25, but it might be later*

**Comment by Valeri0p** [comment]
Thanks for continuing the articles 👍 so much things happened, for the better or worse...
Probably the most interesting piece of code is this: https://github.com/CTCaer/hekate/pull/51

**Comment by leo60228** [comment]
maybe mention Fuji? it's my toolkit for celeste custom maps on the switch
