### ISSUE TITLE
Setup development issues 

### ISSUE THREAD

**Issue by Pokemod97** [ReswitchedWeekly/ReswitchedWeekly.github.io#8]
Cmake version. llvm-5 and lld-5 is also needed

**Comment by roblabla** [comment]
And lz4

**Comment by roblabla** [comment]
Also I removed mephisto, because I got lazy. Need to do a full section on it.

**Comment by Pokemod97** [comment]
requiremensts.txt

**Comment by roblabla** [comment]
Python/Pip also need to be installed. Along with https://github.com/reswitched/libtransistor/blob/master/requirements.txt

**Comment by roblabla** [comment]
Also need to talk about Ace Loader's STDIO setup (using `ncat -kl 2991`).

**Comment by blockfeed** [comment]
For xenial users -
* needs to import the "Install (qualification branch)" archive signature
* based on recent events, there might need to be a mention of checking out `graphics-experimental-fs` and doing a submodule update?

**Comment by blockfeed** [comment]
more xenial notes: 
package is named python-pyelftools

as far as requirements.txt -- xenial lz4 is bunk, you need the pip version:
sudo apt-get remove python-lz4
sudo apt-get install python-pip
sudo pip install lz4

**Comment by blockfeed** [comment]
additional xenial notes: 
git clone --recursive https://github.com/reswitched/libtransistor
cd libtransistor/
git checkout graphics-experimental-fs
git submodule update
make LLVM_POSTFIX=-5.0

**Comment by Ehnoah** [comment]
From my review yesterday, as you guys helped me I think this is it:

NodeJS
https://nodejs.org/en/download/package-manager/

**Pythong-Pip**
apt-get install python-pip

**Python Module**
pip install lz4
pip install pyelftools

**Clang / llvm / lld**  (I hope it include LLVM)
https://apt.llvm.org/
apt-get install clang-5.0 lldb-5.0 lld-5.0  

**Cmake** 
apt-get install cmake

**Netcat** for the ACE_LOADER
apt-get install netcat

**Comment by roblabla** [comment]
ace_loader.nro -> ace.nro

**Comment by roblabla** [comment]
Most of those were fixed. I'll make separate issues for the remaining things.
